version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          # start-command: 'npm run start'
          # cypress-command: 'npm run cypress run --parallel --record --group all tests'
          cypress-command: |
            'ls -la'
            'mkdir ./cypress/videos ./cypress/screenshots'
            'npm run test:parallel'
          parallelism: 2